version: '3.9'

services:
  odoo18:
    build: .
    container_name: odoo18-dev
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - odoo_data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: sleep infinity
    networks:
      - odoo18_network

  db:
    image: postgres:15
    container_name: odoo18-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    networks:
      - odoo18_network

volumes:
  odoo_data:

networks:
  odoo18_network:
    driver: bridge