services:
  odoo-mut-14:
    build: .
    container_name: odoo-mut-14
    command: sleep infinity
    ports:
      - "10700:8069"
    depends_on:
      - db-mut-14
    volumes:
      - ./extra-addons:/workspace/extra-addons
    networks:
      - odoo_network

  db-mut-14:
    image: postgres:13
    container_name: db-mut-14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge