[options]
admin_passwd = adminadmin
addons_path = /usr/lib/python3/dist-packages/odoo/addons, /workspace/extra-addons/community_modules, /workspace/extra-addons/Mutualizo2.0
db_host = db-mut-19
db_port = 5432
db_user = odoo
db_password = odoo
db_sslmode = prefer
db_template = template0
server_wide_modules = base, web
without_demo = all
data_dir = /var/lib/odoo
csv_internal_sep = ,
http_enable = True
http_interface = 0.0.0.0
http_port = 8069
list_db = True
log_db = True
log_db_level = warning
log_handler = :INFO
log_level = info
max_cron_threads = 4
transient_age_limit = 1.0